export const SURVIVAL_GUIDE_TABS = [
  {
    id: "about",
    icon: "📜",
    label: "About",
    title: "About the Game",
    hasImage: true,
    signatureQuote: "The dead do not seek to be feared... only remembered.",
  },
  {
    id: "story",
    icon: "📖",
    label: "Story",
    title: "Story",
    signatureQuote: "What is forgotten may still echo — if only someone will listen.",
  },
  {
    id: "world",
    icon: "🌍",
    label: "World",
    title: "The World",
    signatureQuote: "Every grave is a book; every world is a chapter.",
  },
  {
    id: "characters",
    icon: "👤",
    label: "Characters",
    title: "Characters",
    signatureQuote: "Behind every name on a stone is a life worth remembering.",
  },
  {
    id: "mission",
    icon: "🎯",
    label: "Mission",
    title: "Your Mission",
    signatureQuote: "You're not here to defeat monsters. You're here to remember.",
  },
  {
    id: "controls",
    icon: "🎮",
    label: "Controls",
    title: "Controls",
  },
  {
    id: "how-to-play",
    icon: "🧩",
    label: "How to Play",
    title: "How to Play",
  },
  {
    id: "mechanics",
    icon: "⚙️",
    label: "Mechanics",
    title: "Game Mechanics",
  },
  {
    id: "tips",
    icon: "💡",
    label: "Tips",
    title: "Tips for New Reapers",
    signatureQuote: "Patience is the light by which the past is best seen.",
  },
  {
    id: "team",
    icon: "👥",
    label: "Team",
    title: "Meet the Team",
    signatureQuote:
      "Giving Our History a New Heartbeat through the Intelligence of Tomorrow.",
  },
  {
    id: "credits",
    icon: "🎵",
    label: "Credits",
    title: "Credits",
    signatureQuote: "The dead have stories to tell. Will you listen?",
  },
];
